### ISSUE TITLE
Many properties only have rdfs:Literal range; could be more specific

### ISSUE THREAD

**Issue by clange** [vocol/mobivoc#10]
I noticed e.g. in https://github.com/mobivoc/mobivoc/blob/master/ChargingPoints.ttl authored by @nfriesen that so far many properties have the range `rdfs:Literal`. Do we want this (say, to keep it simple for our domain experts who don't know the details of RDFS), or should we be more specific? _If_ we want to be more specific, let's choose appropriate XML Schema datatypes, e.g. `xsd:date` or `xsd:string`.

**Comment by der-bruemmer** [comment]
Fixed in general refactoring as of v0.1.1
