### ISSUE TITLE
[Energy.ttl] syntax error, unexpected string literal, expecting .

### ISSUE THREAD

**Issue by np00** [vocol/mobivoc#30]
**Original Line:** 

```
                   "Station de recharge"@fr .

```

 **File:** https://github.com/mobivoc/mobivoc/blob/9b20c1710ae9ab0dbfe3a9861191c313b9970b10/Energy.ttl#L7; 
**Person(s) who edited the file:** @clange

**Comment by der-bruemmer** [comment]
Fixed in general refactoring as of v0.1.1
