### ISSUE TITLE
[Energy.ttl] syntax error, unexpected string literal

### ISSUE THREAD

**Issue by np00** [vocol/mobivoc#31]
**Original Line:** 

```
                   "Charge column"@en ?
```

 **File:** https://github.com/mobivoc/mobivoc/blob/7e82b824b2b58a13a14e8974419ee3d91bb8dc6b/Energy.ttl#L6; 
**Person(s) who edited the file:** @clange

**Comment by der-bruemmer** [comment]
Fixed in general refactoring as of v0.1.1
