### ISSUE TITLE
[Parking.ttl] syntax error at '!'

### ISSUE THREAD

**Issue by np00** [vocol/mobivoc#33]
**Original Line:** 

```
!!11

```

 **File:** https://github.com/mobivoc/mobivoc/blob/639d80261ad89ccd0e358c4a2667945c7441473e/Parking.ttl#L17; 
**Person(s) who edited the file:** @data-whisperer

**Comment by der-bruemmer** [comment]
Fixed in general refactoring as of v0.1.1
