### ISSUE TITLE
Closing the connection loop between description documents and entities they describe

### ISSUE THREAD

**Issue by kidehen** [vocol/mobivoc#36]
As a fundamental pattern, I would encourage the addition of the following relation to each block of class, property, and individuals definitions:

<{entity-uri}> rdfs:isDefinedBy <> . 

Net effect, you have a nice Linked Data closed loop that makes follow-your-nose exploration much better.

**Comment by der-bruemmer** [comment]
Fixed in general refactoring as of v0.1.1
