### ISSUE TITLE
[Aircraft.ttl] syntax error at 't'

### ISSUE THREAD

**Issue by np00** [vocol/mobivoc#37]
**Original Line:** 

```
test value 42 
```

 **File:** https://github.com/vocol/mobivoc/blob/dd7282f4f18a093bef94fc4bca1a96647f348645/Aircraft.ttl#L1; 
**Person(s) who edited the file:** @data-whisperer

**Comment by der-bruemmer** [comment]
Fixed in general refactoring as of v0.1.1
