### ISSUE TITLE
[BikeSharing.ttl] syntax error, unexpected a

### ISSUE THREAD

**Issue by np00** [vocol/mobivoc#39]
**Original Line:** 

```
  as

```

 **File:** https://github.com/vocol/mobivoc/blob/9f5e7f9f6df6b9847d1eafa1c4ffb1ccf2cb4000/BikeSharing.ttl#L14; 
**Person(s) who edited the file:** @np00

**Comment by der-bruemmer** [comment]
Fixed in general refactoring as of v0.1.1

**Comment by der-bruemmer** [comment]
Fixed in general refactoring as of v0.1.1
