### ISSUE TITLE
Discuss versioning scheme

### ISSUE THREAD

**Issue by nucknorris** [vocol/mobivoc#46]
In order to continuously develop and also use MobiVoc at the same time, we need to provide versions. This would ensure backwards compatibility.

Possible solutions:

http://schema.mobivoc.org/1.0.0/

or

http://schema.mobivoc.org/2018/01/

**Comment by np00** [comment]
Both have their advantages and disadvantages. I am not decided yet.

But `schema.mobivoc.org` should always point to the latest version & shoud not forward to an URL with version information (in my opinion).

**Comment by np00** [comment]
I close the ticket since we have the 1.0.0 solution in place. 

http://schema.mobivoc.org/#1.0.0/
