### ISSUE TITLE
RealTimeCapacity: dcterms:date

### ISSUE THREAD

**Issue by pietercolpaert** [vocol/mobivoc#49]
The class [mv:RealTimeCapacity](http://schema.mobivoc.org/RealTimeCapacity) says dcterms:date is in its domain. However, shouldn’t we be more precise and for instance use dcterms:modified to explain when this resource was last changed?

**Comment by np00** [comment]
Thanks for the pointer. 

Specifying rdfs:domain with mv:RealTimeCapacity to either dct:date or dct:modified is not optimal: It would mean that any instance in the future would be typed as such, which is not in our interest :) 

I will certainly remove it and review that part.
