### ISSUE TITLE
Add MobiVoc logo and links to GitHub and the main Website to the Parrot generated ontology documentation

### ISSUE THREAD

**Issue by soeren1611** [vocol/mobivoc#9]

**Comment by np00** [comment]
Logos exist on both, the GitHub ReadMe and the homepage.

Various documentation links exist as well: 
Human-friendly version (HTML) on the MobiVoc homepage: http://schema.mobivoc.org/
Deployed on Linked Open Vocabularies: https://lov.linkeddata.es/dataset/lov/vocabs/mv
WebVOWL visualization: http://www.visualdataweb.de/webvowl/#iri=http://schema.mobivoc.org/
OOPS report: http://oops.linkeddata.es/response.jsp?uri=http://schema.mobivoc.org/
